#include <stdio.h>
#define NUMBER_ARGS 3
#define FORMAT_FLAG_POSITION 1
#define FORMAT_FLAG_SPAN 4
#define FORMAT_FLAG "-fmt"
#define FORMAT_TYPE_POSITION 2
#define FORMAT_TYPE_GREGORIAN "AAAAMMDDHHmmSS"
#define FORMAT_TYPE_JULIAN "AAAADDDHHmmSS"
#define FORMAT_TYPE_GREGORIAN_SPAN 14
#define FORMAT_TYPE_JULIAN_SPAN 13
